DamonOehlman/detect-browser

browser.js

Array's map and filter functions are available only from IE9. This modification allow the code to be ran on older browser.
Also renamed a function, have two things with the same name is not a best practice.
Documentation:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

Removed map() and filter() usage

---

browser.js

edge also has "Chrome" in its UA, so it was being detected as chrome

fix bug where edge was detected as chrome

---

lib/detectBrowser.js
test/logic.js

fixes #15
more recent versions of opera have adopted a UA string that closer
resembles that of chrome, and is currently falsely detected as such.

account for updated opera UA strings

---

test/logic.js

I believe the intent was `expectedResult` not `extectedResult`

Fix grammatical error in test helper

---

lib/detectBrowser.js
package.json

This addresses the use of `.fill` for IE11 and older.

Fix .fill issue in IE 11

---

browser.js
lib/detectBrowser.js
test/logic.js

Added error handling for when `navigator` does not exist. Useful for isomorphic rendering of apps when the `navigator` does not exist server side.

Added null navigator handling

---

lib/detectBrowser.js
test/logic.js

Described here:
https://github.com/DamonOehlman/detect-browser/issues/35
Discovered this UA string in our logs:
`Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0; MSN 11.61; MSNbMSNI; MSNmen-us; MSNcOTH) like Gecko` and it's IE11 per https://browscap.org/ua-lookup

issue #35: modify IE11 regex to match another valid UA string

---

lib/detectBrowser.js
test/logic.js

Firefox on iOS has a different [UserAgent string](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox#Firefox_for_iOS).
Since this was undefined, the `detect-browser` was returning undefined.

Add FxiOS to list of browsers

---

README.md
index.js
package-lock.json
test/logic.js

@DamonOehlman
Following this issue https://github.com/DamonOehlman/detect-browser/issues/56, this PR aims to allow support Facebook and Instagram in-app browsers :iphone: 
**First commit :** Facebook integration
Use of FBAV ( Facebook app version ) to match the browser  https://developers.whatismybrowser.com/useragents/explore/software_name/facebook-app/
**Second commit :** Instagram integration ( Instagram user-agent examples ->  https://mpulp.mobi/2016/07/12/instagram-user-agent/ )
**Third commit :** Update package-lock.json
**Fourth commit :** Minor fix in readme
Tested on iOS device, works perfectly  :+1:

Facebook/Instagram in-app browser support

---

index.js
test/logic.js

This might be a better path to add data if it might be a bot.
Copied from a ruby lib called agent orange:
https://github.com/kevinelliott/agent_orange/blob/f06c3d59452cd21f52261b16a6ea1a5b9b8ac0db/lib/agent_orange/device.rb#L35

Add bot attribute and test for common bot strings

---

index.js
test/logic.js

Hello @DamonOehlman! I've been using your package in my code but found that I need support for identifying Samsung Internet (the default web browser on Samsung devices). Currently, when the detect-browser package tries to identify a user agent string for Samsung Internet, it identifies it as Chrome. This PR aims to add support for Samsung Internet.
According to Samsung documentation [here](http://developer.samsung.com/technical-doc/view.do?v=T000000203), the user agent string for Samsung Internet on samsung devices requires the text `SamsungBrowser/version`. I followed these guidelines when creating my regex.

Add support for Samsung Internet browser

---

index.js
test/logic.js

Fixes postfixed ios-webview browser.
Some versions of the iOS WebView append a version after Mobile, so the regex has been modified to allow for this.

iOS WebView Fix

---

index.js

So this is a reasonably simple change, but one that should have a pretty big impact for people who have been hit with the code path which is returning a false positive on node detection (see #54).
It changes two things:
1. We do browser detection if at all possible (i.e. `navigator` is defined).  This then falls back to detecting the node environment if that isn't available.
2. Removes the `require('os')` import for os detection and simply uses `process.platform` instead.  The information won't be as detailed and it's possible that a user of this module may still want to opt to do their own check using the `os` module.  Given that the majority use case is web browser detection though I think that makes sense.  Should stop `browserify` bringing in any shims for the `os` module also (which …

prioritize browser detection, remove os dependency

---

index.js

When I run this module through Webpack minification the literal white space in the Instagram regex pattern gets removed and the escape gets placed on the first opening parentheses. Suggest placing white space character check here instead.
Signed-off-by: Blake Cerecero <Blake@DigitalBlake.com>

Fixed instagram regex pattern

---

src/index.ts
tsconfig.json

Additionally, set the `tsconfig.json` file to only expect to have access to `es5` constructs.
Fixes #89.

Remove `Array#find` usage

---

src/index.ts
test/logic.js

iOS version 12.1.4 has a slightly different userAgent for the webview browser. The new version no longer contains the word "Mobile".
Example:
```
iOS 12.1.4:
Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko)
iOS 12.1:
Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16B92
```
This means that the previous regex  `/AppleWebKit\/([0-9\.]+).*Mobile/` doesn't work. I have modified the regex to instead check for `Gecko)` which seems to only appear in the Webview and works for the unit tests in `logic.js`.

Added support for Webview in iOS v12.1.4

---

src/index.ts
test/logic.js

Resolves #97 
UA:
```
Mozilla/5.0 (Linux; U; Android 7.0; en-us; MI 5 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.146 Mobile Safari/537.36 XiaoMi/MiuiBrowser/9.0.3
```
Detection result:
```js
{ name: 'miui', version: '9.0.3', os: 'Android OS' }
```
NOTE - prior to this change the browser would have been detected as a chrome browser, so that will need to be made mention of in the release notes.  This is very similar to the Samsung internet browser behaviour though so shouldn't be an unexpected change to users who might be expecting chrome.

add detection for miui browser

---

src/index.ts
test/logic.js

Will be interesting to see if MS retain the shortened `Edg` vs `Edge` in the user agent string (I doubt it). As such I expect this is a detection that will become redundant as MS transitions to chromium backed edge in stable, but I think it's probably a worthwhile detection to add for now in case anyone wants to give it special treatment in the interim.
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.48 Safari/537.36 Edg/74.1.96.24
```

add detection for new edge chromium browser

---

.prettierrc
package.json
src/index.ts
test/logic.js
yarn.lock

This commit brings the source file formatting inline with what `prettier` would choose, so future PRs won't introduce whitespace noise.
Note the addition of the manual `yarn autoformat` command also which manually runs `prettier` against the `src` and `test` directories.

chore: install prettier so I am not fighting format on save

---

src/index.ts

Fixes #115 
Updated `index.d.ts` looks like this so looks good.
```ts
/// <reference types="node" />
interface DetectedInfo<N extends string, O, V = null> {
readonly name: N;
readonly version: V;
readonly os: O;
}
export declare class BrowserInfo implements DetectedInfo<Browser, OperatingSystem | null, string> {
readonly name: Browser;
readonly version: string;
readonly os: OperatingSystem | null;
constructor(name: Browser, version: string, os: OperatingSystem | null);
}
export declare class NodeInfo implements DetectedInfo<'node', NodeJS.Platform, string> {
readonly version: string;
readonly name: 'node';
readonly os: NodeJS.Platform;
constructor(version: string);
}
export declare class BotInfo implements DetectedInfo<'bot', null, null> {
readonly bot: true;
readonly name: 'bot'; …
```

export Browser and OperatingSystem literal types

---

src/index.ts
test/logic.js

A potential implementation that addresses the request in #126 
From an implementation perspective I've implemented a result class - `SearchBotDeviceInfo` which adds the `bot` string so that the result of the detection of the UA:
```
Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
```
is:
```
{
name: 'chrome',
version: '41.0.2272',
os: 'Android OS',
bot: 'Googlebot',
}
```
In terms of being able to determine that we have captured one of these new types of results, either the `bot` attribute can be tested, e.g. `typeof result.bot == 'string'` or using the `instanceof` check given the result is a class.  Using a truthy check on the bot …

implementation of a new result type: SearchBotDeviceInfo

---

src/index.ts
test/logic.js

This PR adds a discriminator so people using TypeScript can have a `result.type` and run that in a `switch` statement that provided exhaustiveness checking if desired:
```ts
import { detect } from 'detect-browser';
const result = detect();
switch (result.type) {
case 'browser': {
// ...
break;
}
case 'bot-device': {
// ...
break;
}
case 'bot': {
// ...
break;
}
case 'node': {
// ...
break;
}
}
```

add a type disciminator for the result

---

package.json
yarn.lock

Github reported a vulnerability with the `minimist` package, so figured it was time to give all the devdeps an upgrade.

upgrade devdeps (minimist vulnerability)

---

src/index.ts

I noticed that #8 was open for almost 5 years so I thought I would contribute a PR myself

detect react-native

---

package.json

This should prevent something like #142 happening again in the future.

Ensure full compilation happens prior to publish

---

src/index.ts
test/logic.js

Added CURL as suggested in https://github.com/DamonOehlman/detect-browser/issues/160. It is not 100% as discussed there, instead it follows this pattern (which seems to be more common in-repo for bots):
```js
// "curl/7.64.1"
{
type: 'bot-device',
name: 'curl',
version: '7.64.1',
os: null,
bot: 'curl',
}
```
I also added the corresponding test.

Added CURL

---

src/index.ts

Current Facebook browser regex doesn't seem to correctly handle iOS case:
Sample user agents:
Android Facebook browser:
`Mozilla/5.0 (Linux; Android 10; ONEPLUS A6000 Build/QKQ1.190716.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/93.0.4577.82 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/335.0.0.28.118;]`
iOS Facebook browser:
`Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_1 like Mac OS X) WebKit/8610 (KHTML, like Gecko) Mobile/18D61 [FBAN/FBIOS;FBDV/iPhone8,4;FBMD/iPhone;FBSN/iOS;FBSV/14.4.1;FBSS/2;FBID/phone;FBLC/ru_RU;FBOP/5]`
Not sure which part of the iOS string is the version, please correct me if I made a wrong call with `FBSV/14.4.1`.

Facebook browser on iOS
